### ISSUE TITLE
Draft announcement to update to the banner

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1004]

**Comment by katieekline** [comment]
**Background**

As a USWDS customer 
I would like to be notified of important releases, such as the updated .gov banner,
So that I can make the necessary changes on my site to be up-to-date.

As a USWDS team member
I would like to assist USWDS customers with implementing important releases, such as the .gov banner,
So I am supporting updates of agency sites that use USWDS.

This story is about disseminating the message of a banner update to all USWDS customers. We want to ensure all agency sites that use USWDS are up-to-date by:

- Proactively explaining the importance of the new banner component,
- Instructing USWDS customers on how to implement the new banner component, and
- Providing support for the new banner component.

**Acceptance criteria**

- [ ] Craft a message that clearly and concisely explains the importance of the .gov banner and provides instructions for implementation.
- [ ] Disseminate the message widely to ensure the proper individuals responsible for implementing the banner are notified. 
- [ ] Be available on regular USWDS channels to answer any implementation questions. 

**Tasks to complete this issue**

- [ ] Publish a blog post on designsystem.digital.gov
- [ ] Add short post on Digital.gov
- [ ] Post a message about the banner updates in several channels
- [ ] Email to relevant listservs
- [ ] Include in the Digital.gov newsletter
- [ ] Email the Web Council

**Definition of done**

- [ ] Acceptance criteria met

**Comment by katieekline** [comment]
@afeijoo The [post](https://docs.google.com/document/d/1AVfxtRJLIouhzQzE5QW5nMWCCE7nZpjSsI5aXpr_sxQ/edit?usp=sharing) is ready for your review.

**Comment by afeijoo** [comment]
@thisisdano The [draft blog post](https://docs.google.com/document/d/1AVfxtRJLIouhzQzE5QW5nMWCCE7nZpjSsI5aXpr_sxQ/edit#):lock: for the banner update is ready for your review. After your review, I'll route it through comms for their review and approval.

**Comment by jAigret-Bix** [comment]
Meeting: Dan and Katie 7.28

**Comment by katieekline** [comment]
@thisisdano I've made updates to the blog post and it is ready for your review.

**Comment by afeijoo** [comment]
The draft is approved. Next steps are in https://github.com/uswds/uswds-site/issues/1035.
