### ISSUE TITLE
Add How to Test Websites for Accessibility as a resource

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1009]
As a visitor on the [Embrace Accessibility design principle](https://designsystem.digital.gov/design-principles/#embrace-accessibility)
I would like to see [How to Test Websites for Accessibility](https://digital.gov/resources/how-test-websites-for-accessibility/) listed as a resource
So I can learn more about both manual and automated testing methods to create accessible websites

**Acceptance criteria**

- [ ] Craft the text for for the link on the USWDS website
- [ ] Disseminate the resource in USWDS channels

**Tasks to complete this issue**

- [ ] Add a link to [How to Test Websites for Accessibility](https://digital.gov/resources/how-test-websites-for-accessibility/) listed as a resource on https://designsystem.digital.gov/design-principles/#embrace-accessibility
- [ ] Post a message to promote How to Test Websites for Accessibility in several channels

**Definition of done**
- [ ] Acceptance criteria met

**Comment by brunerae** [comment]
Assigning to @thisisdano for close-out as this is now obsolete due to upcoming work

**Comment by brunerae** [comment]
Closing as this is now obsolete due to our work on accessibility checklists.
