### ISSUE TITLE
Publish banner blog post and announce it

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1035]
This issue is a follow-up to https://github.com/uswds/uswds-site/issues/1004.

**Acceptance criteria**

- [X] Craft a message that clearly and concisely explains the importance of the .gov banner and provides instructions for implementation.
- [ ] Disseminate the message widely to ensure the proper individuals responsible for implementing the banner are notified. 
- [x] Be available on regular USWDS channels to answer any implementation questions. 

**Tasks to complete this issue (see [rollout plan](https://docs.google.com/document/d/1Wjy5NdIXFOjFuCxXr97UUkbepRZHNhPbWwAbQoYd8NU/edit#heading=h.ulnb09ldjuj1) for details)**

- [x] Move [approved content](https://docs.google.com/document/d/1AVfxtRJLIouhzQzE5QW5nMWCCE7nZpjSsI5aXpr_sxQ/edit#) from gDoc to Markdown @allie-shaw 
- [x] Publish a blog post on designsystem.digital.gov `News & Updates`
- [ ] Include video segment of banner update in blog post. [July and August video clips ](https://drive.google.com/drive/u/2/folders/1dnOwoDxQjffLYhNmAnFL5nlwEMgctC7M)
- [x] Add short post on Digital.gov and include in the Digital.gov newsletter
- [x] Post a message about the banner updates in several channels, including relevant listservs

**Definition of done**

- [x] Acceptance criteria met

**Comment by katieekline** [comment]
@thisisdano The [messaging](https://docs.google.com/document/d/1RdlZraNqoXZW85R6-B4on1g1fIr9IUarPi66DQST014/edit?usp=sharing) for the various channels announcing the blog post/banner update is ready for your review.

**Comment by afeijoo** [comment]
Re-opening for the comms rollout steps that remain above.

**Comment by afeijoo** [comment]
@katieekline and @jAigret-Bix Do we still plan to include video segments of banner update in blog post? (See the checklist item above ^^^)

**Comment by afeijoo** [comment]
Comms done. I added https://github.com/uswds/uswds-site/issues/1053 as a new issue to add the video clips.
