### ISSUE TITLE
Update maturity assessment worksheet

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1054]
**Update maturity assessment worksheet**
https://designsystem.digital.gov/files/uswds-maturity-assessment-worksheet-v0.2.pdf

Page 8: "Listen." "Practical actions." `Practical actions` should be replaced with [these 11 practical issues](https://designsystem.digital.gov/design-principles/#listen) 

**Tasks to complete**
- [x] acquire worksheet
- [x] update page 8. `practical actions` 
- [x] review and approval
- [ ] Create PR,  publish updated worksheet

**DoD**
- [ ] All tasks are complete

**Comment by allie-shaw** [comment]
For Review
https://gsa-tts.slack.com/archives/C050HRGN7/p1600960314000900?thread_ts=1600880397.002100&cid=C050HRGN7

**Comment by afeijoo** [comment]
LGTM.

**Comment by jAigret-Bix** [comment]
@mejiaj PR is ready for creation. TY!

**Comment by jAigret-Bix** [comment]
@thisisdano  ready for your review

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds-site/pull/1071
