### ISSUE TITLE
IAAF Presentation: Oct 6

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1062]
[Starter Deck ](https://docs.google.com/presentation/d/10X9HKG2FBRV9fwwwJkNcEvdhdZh859JiQSaxFYJ1jgo/edit)

We are presenting at the 2020 Interagency Accessibility Forum (IAAF) on October 6 from 2-2:25. The format is a ~20 minute presentation followed by Q&A. 

**Topic**
Embrace Accessibility and Build It Into Every Decision - 21st Century IDEA requirements are critical and necessary, but only the beginning. Accessibility is about real people who use our services. Everyone has a role to play in making federal websites and digital services accessible and inclusive. The U.S. Web Design System's Embrace Accessibility principle encourages teams to design generously and celebrate requirements as a set of constraints that help us create better products for all users. Accessibility affects everybody. Build it into every decision.

**Panel Members**
Ammie Farraj Feijoo, General Services Administration
Dan Williams, General Services Administration

**Tasks to Complete**
- [x] Review and finalize deck. See [starter deck](https://docs.google.com/presentation/d/10X9HKG2FBRV9fwwwJkNcEvdhdZh859JiQSaxFYJ1jgo/edit)
- [x] Send deck through appropriate review channels, i.e. comms
- [x] [remediated slides](https://drive.google.com/file/d/1iHRd7ikIDjI8urNMShusi88oEAD4GqU1/view)
- [x]  Present at the 2020 Interagency Accessibility Forum (IAAF) on October 6 from 2-2:25

**Comment by thisisdano** [comment]
OK, reviewed!

**Comment by afeijoo** [comment]
Presented [this deck](https://docs.google.com/presentation/d/1dZrm3emf-CYXfyt7fuesgHWSEbTCFK0S/edit#slide=id.p1) on 10/6.
