### ISSUE TITLE
Cleanup gulp tasks

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#1201]
## Description

- [x] Use `prettier` and `airbnb` ESLint guidelines based on [18F](https://engineering.18f.gov/javascript/#style) - #1200
- [x] Use Gulp v4 style - #1484
  - [x] Tasks in `config/gulp/` need to use consistent style (ex: `var → const` or `function() → () =>`)
- [ ] Remove deprecated features blocked by #1575
  - [x] #1649

**Comment by mejiaj** [comment]
Closed, this work completed in tasks outlined above.
