### ISSUE TITLE
V3 - Update Getting Started for Devs

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#1544]
## Description

Update the [Getting started for developers guide](https://designsystem.digital.gov/documentation/getting-started-for-developers/) to reflect the changes coming with 3.0. 

:warning: This will likely have more items added, but we can get started with the tasks listed for now. 

### [Phase 1, Step 3:](https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/#step-3-install-uswds)
- [x] Update command to `npm install @uswds/uswds --save`
- [ ] update uswds_version in _config.yml to read `3.0.0` (we should probably confirm with James that that is what it should be called). This should update the references to `uswds@3.0.0-beta.5`
- [x] `./node_modules/uswds` should be `./node_modules/@uswds/uswds/`

### [Phase 2, Step 1:](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/#step-2-install-uswds-compile#step-1-set-up-your-projects-sass-entry-point)
- [ ] Mostly TK - need to review more deeply. Will update when ready.
    - Outstanding questions - update `@import` references
- [x] Update `./node_modules/uswds/dist/scss/uswds.scss` to `./node_modules/@uswds/uswds/dist/scss/uswds.scss`

### [Phase 2, Step 4:](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/#step-2-install-uswds-compile) 
- [x] Create a new column in the [paths table](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/develop/documentation/getting-started/developers/phase-two-compile/#step-4-create-path-settings-and-export-compile-functions) to the right of `Default` column called `Default values - Version 3.0`. 
- [x] Relabel the current `Default` column to `Default values - Version 2.x`
- [x] Add the settings found in the [uswds-compile gulpfile.js V3 settings](https://github.com/uswds/uswds-compile/blob/develop/gulpfile.js#L40-46)

**Comment by mahoneycm** [comment]
@mejiaj @amyleadem let me know what we want to do for the `_config.yml` file. I branched off develop and it currently had `uswds_version: 3.0.0-beta.5` which means the reference on the getting started page was already `3.0.0-beta.5`. I can switch it to `3.0.0` if that's what it should look like post release!
