### ISSUE TITLE
USWDS-Site - Feature: Changelog README improvements

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#2234]
### Is your feature request related to a problem? Please describe.

Suggestions for improving Changelog README for consistency, best practices, and improved readability.

1. Rename file `README.md`. This change is consistent with how Github handles their documentation. See [`content/rest/README.md`](https://github.com/github/docs/blob/a12c5d324afa1be644b9eee1ae64aef97882bc93/content/rest/README.md?plain=1#L8) and [`content/graphql/README.md`](https://github.com/github/docs/blob/a12c5d324afa1be644b9eee1ae64aef97882bc93/content/graphql/README.md?plain=1#L8) as examples.
2. Lint markdown file.
3. Alphabetically sort data keys to improve readability and make it consistent to code example in lines 45-63.
    https://github.com/uswds/uswds-site/blob/05451030f486701baba9a6907d85786f4170f226/_data/changelogs/_CHANGELOG-README.md?plain=1#L13-L20
4. Add `affectsContent` and `affectsSettings` to code example on line 45.
5. Use placeholder format for `versionUSWDS: N.N.N` (pattern started in USWDS 3.5.1 release)

## Todo

- [ ] Rename file `_CHANGELOG-README.md → README.md`.
- [ ] Lint and format markdown file.
- [ ] Alphabetically sort `affects` keys in data keys table.
- [ ] Make sure code example on line 45 includes **all** affects data keys.
- [ ] Use placeholder format in USWDS version code example.
- [ ] Change date to expected format `NNNN-NN-NN → YYYY-MM-DD`

>**Note**
>Wrote this as task list so we can spin off into their own separate issues (if needed)

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.
