### ISSUE TITLE
Research page refresh

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2309]
### Purpose
This issue is to organize updates to the USWDS [Research page](https://designsystem.digital.gov/about/research/), housed in the [About section](https://designsystem.digital.gov/about/) of the USWDS website.

### Current state of Research page
- Uses future tense to describe past initiatives
- Reads like a “time capsule” of where the design system was 7 or 9 years ago

### Phase 1
- Publish content that is more evergreen and won’t change quickly
- Collect past and ongoing research that is relevant to the USWDS community and the public
              - [Inclusive design patterns](https://designsystem.digital.gov/together/) 
              - [Transforming the American digital experience](https://designsystem.digital.gov/next/) 
              - Top tasks research 
              - [Recent UX testing with participants who have disabilities](https://github.com/uswds/uswds/wiki/Usability-research-findings-for-Q3-2023)
- [Recruitment page](https://docs.google.com/document/d/1n5soFmfRVlXUmPt2mMfz1MUy3NsDEIPSc-DdfxivVY4/edit#heading=h.gyw8t2b0efeq) 

### Phase 2
- Audit [Research content in GitHub](https://github.com/uswds/uswds/wiki/Research-Strategy) and make recommendations for improvements
- Consider which past research to feature on website Research page
- Continue to prioritize research sharing as team makes bigger IA improvements
- Consider how research on individual components can be leveraged in different places on the site (e.g., on component pages, on research page)

### Task List
- [x] Outline purpose and user goals for research page
- [x] Outline purpose and user goals for recruitment page
- [x] #2340
- [x] Draft content for main research page
- [x] Edit and finalize content for main research page
- [x] #2354
- [x] Draft content for research recruitment page (for public)
- [x] #2274 
- [x] Publish recruitment page (for public)
- [x] #2463
- [x] Publish feds-only recruitment page 
- [x] Review research content on GitHub and flag opportunities to update and improve

**Comment by jaclinec** [comment]
I am currently working on a [research page draft](https://docs.google.com/document/d/1Lx-oUHboZ33aUt4XYyNU--SB_1_6Je-LHyLYHVRRCD0/edit?usp=sharing) outlining user profiles, goals, and content outline for the research page.

**Comment by annepetersen** [comment]
Do we expect this to be done by Friday? We'd like to be able to publish by monthly call on the 16th.

**Comment by jaclinec** [comment]
Flagging that we may need to hold off on including "How to participate" and the recruitment pages for now (especially for recruiting feds) until we get Qualtrics and create the signup form. The signup form for the public is a Google form - wondering if that is ok or if we have to use Qualtrics for that as well.

**Comment by annepetersen** [comment]
Should we update with the fed recruitment now that that's up?

**Comment by jaclinec** [comment]
Yes, I updated the task list above to account for it. We have [drafted the content](https://docs.google.com/document/d/1UoaxVKe9iKwUvH7U26Xgx6l5PZR2ZHRsFHf0t-i0hvk/edit?usp=sharing) but I haven't looked at it in a while. I will need to edit it so that it follows similar language that we use on the recruitment page for the public.

**Comment by annepetersen** [comment]
Dropped some edits into that doc

**Comment by brunerae** [comment]
@jaclinec / @sarah-sch this Issue is done and can be sent to FFR for final closure, right?

**Comment by jaclinec** [comment]
@brunerae yes this issue is done. Thanks!

**Comment by sarah-sch** [comment]
I'm closing this issue because all of the checklist items have been completed.
