### ISSUE TITLE
Archive Performance pages on USWDS website

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2331]
# Purpose
As part of the [content audit](https://github.com/uswds/uswds-team/issues/309), we discovered that the [Performance section](https://designsystem.digital.gov/performance/) of the website is out of date. We need to address this issue to make the site more useful and trustworthy.

# Current state of Performance pages
The most substantive pages in this section are out date and reflect guidance and research that are several years old. 

# Our goals
The team has decided to archive these pages in the short term. Time permitting, in the future we may pull useful evergreen content from this section to display on the site

# Task list

## 1 Month
- [ ] Decide where to redirect URLs
- [ ] [Inform Digital.gov](https://digital.gov/topics/performance/) (and others as needed) of achieving decision
- [ ] Archive Performance section of site

## 3 months
- [ ] Consider whether it would be useful to point our users to[ Digital.gov's performance page](https://digital.gov/topics/performance/) or another government resource
- [ ] Gather evergreen content from archived performance section to draft more useful performance page

**Comment by brunerae** [comment]
We've decided against archiving this content. I've created two Issues #2542 and #2543 to capture what updates we've decided to make to this section. I am closing this Issue as `Status: Decided Against`.
