### ISSUE TITLE
Review content on USWDS Video Tutorials page

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2333]
### Purpose
Via Zendesk a user has flagged that videos on the [Video tutorials page](https://designsystem.digital.gov/documentation/video-tutorials/) are unavailable. The need to rethink this page was also noted in the [content audit](https://github.com/uswds/uswds-site/issues/2341). The purpose of this issue is to evaluate this page and make appropriate upates.

### Current State of Page
4 of 5 video tutorials on this page are unavailable, and the choice of videos (e.g., "U.S. Web Design Standars 1.0 Launch Updates") seem outdated.

### Goal
Eliminate unavailable videos and decide whether more useful content can be embedded on this page.

### Task List
- [x] Discuss with team which, if any, video tutorials should be displayed here.
- [x] Provide updated copy.
- [ ] Make page updates.

**Comment by sarah-sch** [comment]
@amyleadem, I put together some quick copy for the[ new Monthly Call page](https://docs.google.com/spreadsheets/d/1pjgWAKI76cZDMFG2cMWVWiLVB-IIzzFcbgkOCH_7GRI/edit?usp=sharing) that we discussed yesterday. Let me know if you have any questions. 

cc @annepetersen @thisisdano

**Comment by mejiaj** [comment]
An alternative solution would be to link to the [USWDS youtube playlist](https://www.youtube.com/playlist?list=PLd9b-GuOJ3nGqDYCNsCMHCQ9MdD5jfB01) from DigitalGov. Or the [DigitalGov past events page](https://digital.gov/events/#events-past).

We could embed the playlist too, if having them leave the site is a concern.

**Comment by sarah-sch** [comment]
@mejiaj, @amyleadem  - I like the idea of embedding the playlist because that way we wouldn't have to remember to update the videos every month. Thanks!

**Comment by amyleadem** [comment]
@sarah-sch @mejiaj 
I embedded the playlist on the [monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-monthly-call-page/about/monthly-calls/). I had a couple of questions:

- It looks like it defaults to show only the most recent video in the playlist, with an icon that opens a menu to show thumbnails of other playlist videos. I'm a bit concerned that users might not immediately understand that there are more videos in the playlist. Maybe we can add some copy that explains that there are more available with a link to the full playlist? We could also investigate digging into the YouTube API for other display options, but that increases the complexity quite a bit, and I'm not even sure what options we have there.  
- Are we sure that this playlist will only ever have monthly calls on it?
