### ISSUE TITLE
USWDS-Site - Add known issues to component pages

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2375]
## Tasks
- [x] Work with Jacline to identify which items should be flagged as "known issues" on site. 
    - Outcome: Jacline created a list of known issues in [this document](https://docs.google.com/document/d/1f4ZiCkqU-qB-utPrkaLP7i_Gu3nhernCtHKZEsfV3C0/edit) (Google Docs :lock:)
- [ ] Update all flagged issues so that they follow the [usability findings issue template](https://docs.google.com/document/d/1ON_UY0aF8Z6tlwiPFzbjwcn51YitVTTH3B9fSaES40Q/edit)
- [ ] Add flagged issues to the "known issues" section on component pages

## Related issues
This work is related to the known issues prototype created in issue https://github.com/uswds/uswds-site/issues/2297.
