### ISSUE TITLE
Content Audit: Align on metrics of success

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2408]
We have outlined the following goals for this content audit of the [USWDS website](https://designsystem.digital.gov/):
- Gather basic descriptive and performance data for all pages
- Combine with top tasks results
- Identify obsolete and redundant content
- Gauge and report on site’s adherence to web content best practices
- Gauge and report on site’s adherence to accessibility best practices
- Use data to inform IA and content improvements

[Documents related to the content audit](https://drive.google.com/drive/folders/1XU8xm1nUGG0VU1ogPZUfXkKQdXsbZss_?usp=drive_link) of the USWDS website are located in the project Google Drive.

In order to consider the team aligned on metrics of success, the following tasks should be done:
- [ ]  The team has been informed of the results of analysis and the site's adherence to web content and accessibility best practices
- [ ] Team has aligned on improvements that need to be made to USWDS website, as well as on a plan and timeline for making those improvements.
- [ ] Team has aligned on a strategy for integrating analytics data into content work going forward.
- [ ] Team has aligned on what a repeatable content audit looks like and recommended timelines for future audits.

**Comment by sarah-sch** [comment]
This work is still in progress. May be difficult to prioritize during the sprint starting 2/26 because of scheduled out-of-office time on content team and scheduled comms work.

**Comment by sarah-sch** [comment]
Sharing metrics of success that team discussed on 4/17/2024:

- Review 25% of site pages not reviewed for TTS audit per quarter
- Aim to measurably improve pace of content bug fixes on site  in next PI (1 and 3 points)
- Aim to measurably improve pace of more substantive content updates in next PI (7 points)
- Reach and sustain siteimprove QA score above 90% in next PI
- Work with team to start distributing a monthly readout of Touchpoints survey data to inform our work

**Comment by thisisdano** [comment]
LGTM
