### ISSUE TITLE
CC a11y: publish file input checklist

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2431]
Follow-up from https://github.com/uswds/uswds/issues/5598

### A11Y
- [ ] Review checklist content
- [ ] Final approval of checklist content

### Content
- [ ] Draft checklist content and send for review with A11Y
- [ ] Final edits to checklist content

### Dev
- [ ] Create PR for checklist content edits and request review by A11Y and CS

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
Gherkins are entered and ready for review, @amycole501 and @alex-hull :)

**Comment by alex-hull** [comment]
Added one more criteria, and I think once it is revised, we can move this on to devs!

**Comment by alex-hull** [comment]
@finekatie The gherkin for the last criteria looks good! @amyleadem File input is ready for devs.

**Comment by finekatie** [comment]
We discussed issues with one of the tests today. Language resolved around passing with exceptions. Not sure what's needed next.

**Comment by amycole501** [comment]
I think content is done; should be passed back to dev for finalizing.

**Comment by finekatie** [comment]
Hi @amycole501 , who is passing to dev - and do you mean for building out the content on site?

**Comment by alex-hull** [comment]
@RachelCorsino and @amyleadem Unsure if y'all saw this. But this should be ready for dev review...again lol.
