### ISSUE TITLE
CC a11y: publish text input checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2439]
Follow-up from https://github.com/uswds/uswds/issues/5553

### A11Y
- [ ] Review checklist content
- [ ] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [ ] Final edits to checklist content

### Dev
- [x] #2628

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by sarah-sch** [comment]
Drafted content on 5/7. Flagged queries for @amycole501 and @alex-hull.

**Comment by sarah-sch** [comment]
@amycole501 and @alex-hull - do you approve of this copy? I noticed that there isn't gherkin text in cell K206. Is copy needed for that test?
