### ISSUE TITLE
CC a11y: publish side navigation checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2443]
Follow-up from https://github.com/uswds/uswds/issues/5726

### A11Y
- [ ] Review checklist content
- [ ] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [ ] Final edits to checklist content

### Dev
- [ ] Create PR for checklist content edits and request review by A11Y and CS

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
Starting gherkins today.

**Comment by finekatie** [comment]
Gherkins done for side-nav and ready for review, @alex-hull  and @amycole501 !

**Comment by amycole501** [comment]
Reviewed, they all read well to me!

**Comment by alex-hull** [comment]
I reviewed as well and left one outstanding comment for @amycole501!

**Comment by finekatie** [comment]
Is this ready to go to dev for review now? Who gets pinged?

**Comment by alex-hull** [comment]
Yes. This is ready to go. @amyleadem @RachelCorsino @cathybaptista This is ready for y'all!

**Comment by brunerae** [comment]
This is live: https://designsystem.digital.gov/components/side-navigation/accessibility-tests/
