### ISSUE TITLE
CC a11y: publish in-page navigation checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2453]
Follow-up from https://github.com/uswds/uswds/issues/5735

### A11Y
- [ ] Review checklist content
- [ ] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [ ] Final edits to checklist content

### Dev
- [ ] Create PR for checklist content edits and request review by A11Y and CS

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
Started work on this today.

**Comment by finekatie** [comment]
Hi @amycole501 and @alex-hull , these are ready for review ! There's one with an n/a and question mark because I'm not sure if you want anything for it, but let me know :)

**Comment by amycole501** [comment]
@finekatie these read well to me!

**Comment by finekatie** [comment]
Yay! @amycole501 who does this go to now for further review?

**Comment by alex-hull** [comment]
@amycole501 I'm tagging the dev squad. @amyleadem @RachelCorsino @cathybaptista This is ready for y'all!

**Comment by brunerae** [comment]
This is live: https://designsystem.digital.gov/components/in-page-navigation/accessibility-tests/
