### ISSUE TITLE
CC a11y: publish footer checklist - create content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2457]
Follow-up from https://github.com/uswds/uswds/issues/5741

### A11Y
- [x] Review checklist content
- [x] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev
- [x] Create PR for checklist content edits and request review by A11Y and CS

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
Adding this to my queue for gherkin work.

**Comment by finekatie** [comment]
Hi team. Footer gherkin drafts are ready for review.

**Comment by amycole501** [comment]
They all read well to me and are very clear.

**Comment by alex-hull** [comment]
I also think the content looks good, @finekatie

**Comment by mahoneycm** [comment]
@brunerae The PR for the accessibility checklist is in Fed Final! Work is being tracked in #2740 and the work is contributed in #2760. Should we mark this issue as complete?

**Comment by amyleadem** [comment]
@amycole501 This appears to have been completed with #2760. Marking this as fed final review because it looks like it is safe to close.
