### ISSUE TITLE
USWDS-Site - Documentation: Add asset compilation instructions

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-site#2472]
### Is your feature request related to a problem? Please describe.

When users are using a different compiler to compile USWDS code, they often run into issues surrounding USWDS image and font assets. Because of this, we've had multiple requests from users who are using USWDS with a JS framework like Angular, React, or Vite who run into compilation errors because the compiler cannot find the assets.

### Describe the solution you'd like

Enhance compilation documentation to include instructions or note about USWDS asset copying.

### Additional context

Recent issue with resolution in comments:
https://github.com/uswds/uswds/issues/5097

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by amyleadem** [comment]
## Tasks
- [ ] Go through previous customer support responses and create a draft paragraph/steps
