### ISSUE TITLE
USWDS-Site: Documentation updates for release 3.8.0

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-site#2477]
# Summary
Changelogs for all updates in the USWDS 3.8.0 release.

## Todo

- [x] Button group changelog
- [x] Validation & Text input changelogs
- [x] Update preview links
- [x] Add scrollable table demo fix
- [x] Remove bumped features

### Documentation page template

- Preview: [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-doc-template/templates/documentation-page/#latest-updates)
- PR: uswds/uswds#5681
- Changelog: #2495

### Checkbox

- Preview: [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5713/components/checkbox/#latest-updates)
- PR: uswds/uswds#5713
- Changelog: #2482

### In-page nav

- Preview:
   - [Documentation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-docs-5444/components/in-page-navigation/#in-page-navigation-initialization-properties)
   - [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-docs-5444/components/in-page-navigation/#latest-updates)
- PR: uswds/uswds#5444
- Changelog: #2252

### Button 

- Preview:
   - [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-enhancement-button-icons/components/button/#latest-updates)
   - [Settings entry](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-enhancement-button-icons/documentation/settings/#component-settings:~:text=Icon%20gap,and%20svg%20icon.)
   - [Settings changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-enhancement-button-icons/documentation/settings/#changelog)
- PR: uswds/uswds#5398
- Changelog: #2207

### Button group 

- Preview: [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-button-group/components/button-group/#latest-updates)
- PR: uswds/uswds#5657
- Changelog: #2498

### Datepicker 

- Preview: [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5701/components/date-picker/#latest-updates)
- PR: uswds/uswds#5701
- Changelog: #2483

### Validation and Text input

- Preview: 
   - [Validation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-validation-text-input/components/validation/#latest-updates)
   - [Text input](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-validation-text-input/components/text-input/#latest-updates)
- PR:  uswds/uswds#5233
- Changelog: #2497

### Table

- Preview:
   - [Documentation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-documentation-5420/components/table/#sticky-table-headers)
   - [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-documentation-5420/components/table/#latest-updates)
   - [Settings](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-documentation-5420/documentation/settings/#tables)
   - [Settings changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-documentation-5420/documentation/settings/#changelog)
- PR: uswds/uswds#5420
- Changelog and documentation: #2229

#### Scrollable examples

- Preview:
  - [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-table-demo/components/table/#latest-updates)
  - Changelog PR: uswds/uswds-site#2501

### Form

- Preview: [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-disabled-color-contrast-changelog/documentation/settings/#changelog) 
- PR: uswds/uswds#5455
- Changelog: #2254

### Footer

- Preview: [Changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5675/components/footer/#latest-updates)
- PR:  uswds/uswds#5675
- Changelog: #2484

## No documentation changes needed

- USWDS - Dependencies: update gulp-mocha
   - PR: https://github.com/uswds/uswds/pull/5680
   - Changelog: N/A - Dependency bump; no user-facing change
- USWDS - Dependencies: Remove experimental module work from core
   - PR: https://github.com/uswds/uswds/pull/5673
   - Changelog: N/A - Dependency bump; no user-facing change
- ~USWDS: Remove outdated normalizations~
   - ~PR: https://github.com/uswds/uswds/pull/5555~
   - ~Changelog: N/A - No user-facing change~

**Comment by amyleadem** [comment]
Draft release notes. Will continue to revise. 

## Features

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`usa-checkbox`, `uswds-core` | Yes | - | - | Added styles for indeterminate checkboxes. Thanks @lpsinger! (# )
`usa-in-page-nav` | - | - | - | Added the ability to customize which headings will be pulled into the in-page navigation link list. Use the new `data-heading-elements` attribute to designate the heading levels that should be included in the component. (#5444)
`usa-table` | - | - | - | Created the `.usa-table--sticky-header` variant to allow sticky positioning on table headers. (#5420)
`usa-table` |   |   |   | Added `$theme-table-background-color` and `$theme-table-sticky-top-offset` settings. (#5420)
`usa-header`, `usa-nav` | - | - | - | Updated the behavior of the mobile header navigation to stay open while loading a new page.(#5513)
`usa-validation` | - | - | - | Added `textarea` support in the validation component. (#5233) Thanks @danbrady!

## Bug fixes

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`usa-button`, `uswds-core` | - | - | - | Improved the vertical alignment of `usa-icon` elements inside of `usa-button`. Spacing can be adjusted using the `$theme-button-icon-gap` setting. (#5398)
`usa-button`, `usa-checkbox`, `usa-combo-box`, `usa-file-input`, `usa-radio`, `uswds-core` | Yes | - | - | Added color contrast checks for disabled tokens. On compilation, USWDS will test disabled element color contrast and provide a fallback color if minimum contrast is not met. If the fallback does not meet minimum requirements, a warning will be provided.(#5455)
`usa-button-group` | - | - | - | Improved button group styles so that button heights match when text wraps to multiple lines.  (#5657) Thanks @aduth!
`usa-date-picker` | Yes | - | - | Added focus styles to calendar button in high contrast mode. Now, the calendar icon changes to the highlight high contrast token on focus. (#5701)
`usa-footer` | - | - | - | Fixed a bug that caused some grid utility classes to be ignored when used inside `usa-footer`. (#5675)
`usa-layout-docs` | Yes | - | - | Updated the visual order of the documentation page to match the HTML order. Now, the side navigation is visually displayed before the main content at narrow screen widths. (#5681)
`uswds-elements` | - | - | - | Removed outdated styles from `normalize.scss` (#5555) Thanks @aduth!

**Comment by amyleadem** [comment]
Sass notifications draft

```sass
3.8.0
Details: github.com/uswds/uswds/releases/tag/v3.8.0


```
