### ISSUE TITLE
CC a11y: publish Character Count checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2487]
Follow-up from https://github.com/uswds/uswds/issues/5448

### A11Y
- [x] Review checklist content
- [x] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev
- [ ] #2532

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by sarah-sch** [comment]
Sarah beginning work on copy 3/22/2024

**Comment by sarah-sch** [comment]
Continuing work on character count text week of 3/25. Passed some technical questions to @amycole501 and @alex-hull on 3/27 and will finalize text after reviewing their answers.

**Comment by sarah-sch** [comment]
Closing this issue because remaining work is captured by #2532 (create PR)
