### ISSUE TITLE
CC a11y audit: publish Tag checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2489]
Follow-up from https://github.com/uswds/uswds/issues/5451

### A11Y
- [x] Review checklist content
- [x] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev
- [ ] #2526

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by sarah-sch** [comment]
Closing this issue because remaining work for this checklist is captured in #2526
