### ISSUE TITLE
CC a11y: publish Tooltip checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2524]
Follow-up from https://github.com/uswds/uswds/issues/5452

### A11Y
- [x] Review checklist content
- [ ] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev Issue
- [ ] #2525

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)
