### ISSUE TITLE
CC a11y: publish Banner checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2641]
Follow-up from https://github.com/uswds/uswds/issues/5511

### A11Y
- [ ] Review checklist content
- [ ] Final approval of checklist content

### Content
- [ ] Draft checklist content and send for review with A11Y
- [ ] Final edits to checklist content

### Dev
- [x] #2642

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)
