### ISSUE TITLE
USWDS-Site: Add documentation updates for uswds-compile 1.2.0

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2749]
## Summary
Update documentation to match the changes in uswds-compile release 1.2.0. 

### Tasks
- [x] Update references to gulp 4
- [x] Add documentation for new `settings.compile.sassSourcemaps` setting
- [x] Add changelogs where needed
