### ISSUE TITLE
USWDS-Site: Outline content types for the What's new page

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2889]
## Summary
Audit current content types from [News and updates page ](https://designsystem.digital.gov/about/updates/ ), research and recommend updated types to use on revived What's New page.

Related doc: [What's New page content types](https://docs.google.com/document/d/1PcsW9ig4XJZuEVSRK-x6Q1g09IZipnCajKqEY0rmw2U/edit#heading=h.htbunyk692vl)

## Task List:

- [x] research and recommend types
- [x] discuss with team/review
- [ ] finalize and get FFR

### Considerations:
Archiving content
Change logs

**Comment by finekatie** [comment]
This has been underway and a doc is created (see above). Discussed some details with Amy L and Jayme C today. More discussion and refinement to be done.

**Comment by finekatie** [comment]
Have created sample content for Amy L to use in prototype.

**Comment by finekatie** [comment]
Prototype is done and waiting for a FFR.

**Comment by thisisdano** [comment]
Thank you!
