### ISSUE TITLE
USWDS-Site - What's new: Update post preview styles

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2953]
## Summary
Redesign the "What's new" post preview design. 

Current design:
![Image](https://github.com/user-attachments/assets/140ea957-fcfe-4fa5-b128-1e3a99b0d1e4)

## Tasks
- [ ] Condense presentation height of post - reduce size of header text, etc
- [ ] Reconsider `h1` structure on post previews
- [ ] Figure out appropriate link structure - should we have both a link on the header and a secondary link?
    - Consider external link icon on title
- [ ] Possibly explore filters

Notes from @finekatie in [PR #2855](https://github.com/uswds/uswds-site/pull/2855#issuecomment-2460825774):
> Hi @amyleadem , per discussion today in CS/UX sync, below is clarification of link styling for our content types (Blurb, Article summary and Article post) that will sit on the What's New page.
> 
> For the Blurb type (short summary that links to a page on USWDS site or GitHub):
> 
> Title of the blurb does NOT have an active link or link styling.
> A link appears below the short summary that gives good info about where the user is going (eg, "Join our discussion on GitHub to share your ideas")
> For the Article summary type (short summary that only links to a longer full article on the USWDS site):
> 
> Title links to the article page
> A link appears below the short summary that has some information for the user and is not duplicative of other links (eg,"Read more about what’s next for USWDS")
> For the Article post type (the article itself)
> 
> Title does not link to anything.
> Links may appear in the text of the article as appropriate to the content within
> Let me know if you have any questions! Here's my [Content Types](https://docs.google.com/document/d/1PcsW9ig4XJZuEVSRK-x6Q1g09IZipnCajKqEY0rmw2U) doc. It's not going to say much more than this, but it's here.
