### ISSUE TITLE
USWDS-Site: Update documentation site for 3.11.0

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2990]
## Summary
Update the website with the changes from USWDS release 3.11.0.

## Tasks
- [ ] Include changelogs for all user-facing changes
- [ ] Update the 3.10.0 references in config.yml file to 3.11.0
- [ ] Add any other other documentation updates related to 3.11.0
