### ISSUE TITLE
USWDS-Site: Documentation updates for 3.12.0

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#3017]
## Summary
Update the website with the changes from USWDS release 3.12.0.

## Tasks
- [ ] Include changelogs for all user-facing changes
- [ ] Update the 3.11.0 references in config.yml file to 3.12.0
- [ ] Add any other other documentation updates related to 3.12.0

**Comment by amyleadem** [comment]
Marking this as "on hold" while we wait for OSC approval on 3.12.0

**Comment by dct2023** [comment]
@uswds/feds Is this one that can go into our OSC Review status?
